name: Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r azure_function/requirements.txt
          pip install -r azure_function/requirements-dev.txt

      - name: Run tests
        run: pytest tests/bronze

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A118B52594B443BBBE412D10F9AE5648 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B52BF075D664271AD31EBE402EE3DAC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_02DE3230AF1A465A92ADF006515FC8E0 }}

      - name: Prepare package
        run: |
          pip install -r azure_function/requirements.txt --target .python_packages/lib/site-packages
          cp azure_function/function_app.py .
          cp azure_function/host.json .
          cp azure_function/requirements.txt .
          rm -rf azure_function

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: spotify-data-pipeline
          package: '.'