name: Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r azure_function/requirements.txt
          pip install -r azure_function/requirements-dev.txt

      - name: Run tests
        run: pytest tests/bronze

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Prepare package
        run: |
          cp -r spotify_data_pipeline azure_function/
          cp azure_function/function_app.py .
          cp azure_function/host.json .
          cp azure_function/requirements.txt .

      - name: Debug structure
        run: ls -la && ls -la azure_function/

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: spotify-data-pipeline
          package: '.'
